name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello there! Thanks for the issues! Repository author/contributor will review and fix soon."
        pr-message: "Hello! Thanks for the PR. Repository author will review soon."
